# Generated by Django 4.2.3 on 2023-07-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_rename_categorias_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
